[tool.poetry]
name = "rorschach-collector"
version = "0.1.0"

authors = ["Dante Devenir <dantedevenir@outlook.com>"]
license = ""

packages = []

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
